### ISSUE TITLE
Fix md5/dm5sum issue digital ocean

### ISSUE THREAD

**Issue by abagayev** [abagayev/stop-russia#14]

**Comment by sobwoofer** [comment]
got error after run script
`root@ubuntu# ./init.sh
./init.sh: line 10: md5: command not found
Error: POST https://api.digitalocean.com/v2/droplets: 422 (request "945f266e-6070-4bd4-8f34-6e42ebf3694e") Only valid hostname characters are allowed. (a-z, A-Z, 0-9, . and -)
`

**Comment by abagayev** [comment]
this is mac/ubuntu issue
