### ISSUE TITLE
Split to paralel

### ISSUE THREAD

**Issue by ggwpqq** [abagayev/stop-russia#16]
Список ресурсов для поражения расщиряется и будет продолжать расширятся. В связи с этим, есть предложение(пока идей по более-менее адекватной реализации не имею) разбить список на несколько частей и запускать паралельно по рандомной цели из каждой части.

Так же думаю стоит поднять количество конектов с 1к до 3-5к.

Список ресурсів для враження росте і продовже рости. У зв'язку з цим, є пропозиція(поки ідей по більщменш адекватній реалізації не маю) розбити список на кілька частин і запускати паралельно по рандомній цілі із кожної частини.

Також думаю варто підняти кількість конектів з 1к до 3-5к.

The list of resources to hit is expanding and will continue to expand. So there is a proposal (so far I have no ideas for a more or less adequate implementation) to split the list into several parts and run in parallel on a random target from each part.

I also think it's worth raising the number of connections from 1k to 3-5k.

**Comment by abagayev** [comment]
гуд айдіа, список вже величезний, я бачу такий розвиток подій - створити два варіанти роботи: рандом і концентрований наприклад з хеш кільцем

таким чином у нас будуть машини що фігачать у різні сторони та машини що рандомно разом обирають одну і ту ж ціль раз на годину

@heetap @nokysin @sobwoofer any ideas?

**Comment by heetap** [comment]
я думаю що ми можемо підняти декілька інстанс зі змінними `random|concentrations ` і взалежності від цьою змінної виконувати запити

**Comment by abagayev** [comment]
пропозиція наступна
https://github.com/abagayev/stop-russia/pull/40

**Comment by abagayev** [comment]
остання версія тут, мержимо як перевіримо, чекаю на людей
https://github.com/abagayev/stop-russia/pull/40
