### ISSUE TITLE
Check logs

### ISSUE THREAD

**Issue by Sinled** [abagayev/stop-russia#21]
для тех кто не очень хорошо знаком с докером и DO может есть мини иснтрукция, что контейнер дейсвительно выполнятся корректно? Судя по графам на дашборде загрузка цпу. пара процентов, и сеть только 30-40 кб/c

**Comment by abagayev** [comment]
Работаем над тюнингом

**Comment by Sinled** [comment]
отвечу сам, может кому пригодится
посмотреть запущенные дроплеты на DigitalOcean

```
 doctl compute droplet list
```


законнектится к дроплету
```
doctl compute ssh <id дроплета> --ssh-key-path <путь к ссш ключу>
```

просмотреть запущенные контейнеры на дроплете
```
docker ps
```

вывести лог того что запущено 
```
docker logs c46c1ad8a0a7
```

**Comment by abagayev** [comment]
в мастере сейчас решение которое добавляет больше потоков, плюс работаем нам скриптом который убивает старые ноды перед поднятием новых, чтобы периодически обновлять в полуавтоматическом режиме

**Comment by abagayev** [comment]
мне кажется что тут решили, закрываю тикет
