### ISSUE TITLE
Single url handling

### ISSUE THREAD

**Issue by maxsharov** [abagayev/stop-russia#23]
Є ідея зробити опцію роботи з певним URL вказуючи його як аргумент в кінці запиту:
```
docker run -ti --rm abagayev/stop-russia <URL>
```

Чи можливо це зробити? Я такий собі Докер юзер, але спробую.

**Comment by ggwpqq** [comment]
Хорошая идея

**Comment by abagayev** [comment]
пропоную використовувати для цього docker compose, інструкція тут:
https://github.com/abagayev/stop-russia/tree/main/automation/compose
